### ISSUE TITLE
Problem installing Particle CLI

### ISSUE THREAD

**Issue by MatejGomboc** [opensourcebeehives/BzBox_ALPHA#2]
Hello, I have difficulties installing Particle CLI. I have tried to install it using Windows installer: https://www.particle.io/products/development-tools/particle-command-line-interface

After install finshes it says I should type "particle setup" in command line. When I do that I get the folowing error:

"Error: Cannot find module 'C:\Users\user\AppData\Roaming\npm\node_modules\particle-cli\bin\particle.js'
       at Function.Module._resolveFilename (module.js:472:15)
       at Function.Module._load (module.js:420:25)
       at Module.runMain (module.js:607:10)
       at run (bootstrap_node.js:420:7)
       at startup (bootstrap_node.js:139:9)
       at bootstrap_node.js:535:3"

**Comment by pnaylor1982** [comment]
Hi,

I don't use the Windows version, but I suggest you make sure all the components are up to date (node.js, npm etc) and go through these tutorials... if you are still having trouble, try posting to the Particle forum.

https://community.particle.io/t/tutorial-particle-cli-on-windows-07-jun-2015/3112
https://docs.particle.io/guide/getting-started/connect/core/#using-windows
https://docs.particle.io/guide/tools-and-features/cli/core/
